
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'sakila_datavault'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'my-snowflake-db'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

vars:
  sakila_source: 'Sakila'

models:
  sakila_datavault:
    warehouse_datavault:
      schema: warehouse-datavault
      hubs:
        materialized: table
        transient: 'true'
      sats:
        materialized: table
        transient: 'true'
      links:
        materialized: table
        transient: 'true'
    staging:
        materialized: view
        schema: staging
    warehouse_kimball:
        materialized: table
        schema: warehouse-kimball
      # Applies to all files under models/example/

## Can snapshots have yml files as documentation like other models???
snapshots:
  sakila_datavault:
    transient: false
