name: testing push to master

on:
  push:
    branches:
      - master

jobs:
  prod:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Install Python Latest
      uses: actions/setup-python@v1
      with:
        python-version: python-latest
      
    - name: Install dbt
      run: |
        python -m pip install --upgrade pip
        pip install dbt
      
    - name: Deploy
      run: |
        dbt run --profiles-dir ./ci_profiles
        dbt test --profiles-dir ./ci_profiles