name: testing push to master based on pull request

on: pull_request

env:
  DBT_PROFILE_TARGET:            dev
  DBT_PROFILE_SNOWFLAKE_ACCOUNT: ${{ secrets.DBT_PROFILE_SNOWFLAKE_ACCOUNT }}
  DBT_PROFILE_USER:              ${{ secrets.DBT_PROFILE_USER }}
  DBT_PROFILE_PASSWORD:          ${{ secrets.DBT_PROFILE_PASSWORD }}
  DBT_PROFILE_ROLE:              A8_USER
  DBT_PROFILE_DB:                DBT_DATAVAULT_TEST
  DBT_PROFILE_WH:                TRAINING_WH

jobs:
  prod:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Install Python Latest
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
      
    - name: Install dbt
      run: |
        python -m pip install --upgrade pip
        pip install dbt
      
    - name: Deploy
      run: |
        export DBT_PROFILE_SCHEMA=pr_$(date +%s)
        dbt run --profiles-dir ./ci_profiles
        dbt test --profiles-dir ./ci_profiles